<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

$relationships = array(
    'users_documents_1' =>
        array(
            'id' => '18b624fe-21da-4f93-180f-55e2e26cb033',
            'relationship_name' => 'users_documents_1',
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'Documents',
            'rhs_table' => 'documents',
            'rhs_key' => 'id',
            'join_table' => 'users_documents_1_c',
            'join_key_lhs' => 'users_documents_1users_ida',
            'join_key_rhs' => 'users_documents_1documents_idb',
            'relationship_type' => 'one-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => 'default',
            'lhs_subpanel' => 'default',
            'from_studio' => true,
            'is_custom' => true,
            'relationship_only' => false,
            'for_activities' => false,
        ),
    'documents_accounts' =>
        array(
            'id' => '1e36d63b-8d00-9c60-154c-55e2e2526673',
            'relationship_name' => 'documents_accounts',
            'lhs_module' => 'Documents',
            'lhs_table' => 'documents',
            'lhs_key' => 'id',
            'rhs_module' => 'Accounts',
            'rhs_table' => 'accounts',
            'rhs_key' => 'id',
            'join_table' => 'documents_accounts',
            'join_key_lhs' => 'document_id',
            'join_key_rhs' => 'account_id',
            'relationship_type' => 'many-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => 'default',
            'lhs_subpanel' => 'default',
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => false,
        ),
    'documents_assigned_user' =>
        array(
            'id' => '23574394-442e-c895-4a65-55e2e237c492',
            'relationship_name' => 'documents_assigned_user',
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'Documents',
            'rhs_table' => 'documents',
            'rhs_key' => 'assigned_user_id',
            'join_table' => NULL,
            'join_key_lhs' => NULL,
            'join_key_rhs' => NULL,
            'relationship_type' => 'one-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => 'default',
            'lhs_subpanel' => 'default',
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => false,
        ),
    'documents_contacts' =>
        array(
            'id' => '28e6c761-31da-7003-3a7c-55e2e2afa344',
            'relationship_name' => 'documents_contacts',
            'lhs_module' => 'Documents',
            'lhs_table' => 'documents',
            'lhs_key' => 'id',
            'rhs_module' => 'Contacts',
            'rhs_table' => 'contacts',
            'rhs_key' => 'id',
            'join_table' => 'documents_contacts',
            'join_key_lhs' => 'document_id',
            'join_key_rhs' => 'contact_id',
            'relationship_type' => 'many-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => 'default',
            'lhs_subpanel' => NULL,
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => false,
        ),
    'leads_documents' =>
        array(
            'id' => '2f800db3-b7ef-e58c-0094-55e2e2d8f72b',
            'relationship_name' => 'leads_documents',
            'lhs_module' => 'Leads',
            'lhs_table' => 'leads',
            'lhs_key' => 'id',
            'rhs_module' => 'Documents',
            'rhs_table' => 'documents',
            'rhs_key' => 'id',
            'join_table' => 'linked_documents',
            'join_key_lhs' => 'parent_id',
            'join_key_rhs' => 'document_id',
            'relationship_type' => 'many-to-many',
            'relationship_role_column' => 'parent_type',
            'relationship_role_column_value' => 'Leads',
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => NULL,
            'lhs_subpanel' => NULL,
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => false,
        ),
    'documents_opportunities' =>
        array(
            'id' => '33f3d493-3cb2-204c-3222-55e2e21114f5',
            'relationship_name' => 'documents_opportunities',
            'lhs_module' => 'Documents',
            'lhs_table' => 'documents',
            'lhs_key' => 'id',
            'rhs_module' => 'Opportunities',
            'rhs_table' => 'opportunities',
            'rhs_key' => 'id',
            'join_table' => 'documents_opportunities',
            'join_key_lhs' => 'document_id',
            'join_key_rhs' => 'opportunity_id',
            'relationship_type' => 'many-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => 'default',
            'lhs_subpanel' => 'default',
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => false,
        ),
    'documents_cases' =>
        array(
            'id' => '3ea15c01-dbf7-b231-c851-55e2e2e474e8',
            'relationship_name' => 'documents_cases',
            'lhs_module' => 'Documents',
            'lhs_table' => 'documents',
            'lhs_key' => 'id',
            'rhs_module' => 'Cases',
            'rhs_table' => 'cases',
            'rhs_key' => 'id',
            'join_table' => 'documents_cases',
            'join_key_lhs' => 'document_id',
            'join_key_rhs' => 'case_id',
            'relationship_type' => 'many-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => 'default',
            'lhs_subpanel' => 'default',
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => false,
        ),
    'documents_bugs' =>
        array(
            'id' => '49bd8f80-ab70-d6f2-9a2c-55e2e2e63536',
            'relationship_name' => 'documents_bugs',
            'lhs_module' => 'Documents',
            'lhs_table' => 'documents',
            'lhs_key' => 'id',
            'rhs_module' => 'Bugs',
            'rhs_table' => 'bugs',
            'rhs_key' => 'id',
            'join_table' => 'documents_bugs',
            'join_key_lhs' => 'document_id',
            'join_key_rhs' => 'bug_id',
            'relationship_type' => 'many-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => 'default',
            'lhs_subpanel' => 'default',
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => false,
        ),
    'securitygroups_documents' =>
        array(
            'id' => '752fb56c-4ac3-4075-3978-55e2e2e8674f',
            'relationship_name' => 'securitygroups_documents',
            'lhs_module' => 'SecurityGroups',
            'lhs_table' => 'securitygroups',
            'lhs_key' => 'id',
            'rhs_module' => 'Documents',
            'rhs_table' => 'documents',
            'rhs_key' => 'id',
            'join_table' => 'securitygroups_records',
            'join_key_lhs' => 'securitygroup_id',
            'join_key_rhs' => 'record_id',
            'relationship_type' => 'many-to-many',
            'relationship_role_column' => 'module',
            'relationship_role_column_value' => 'Documents',
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => NULL,
            'lhs_subpanel' => 'default',
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => false,
        ),
    'aos_contracts_documents' =>
        array(
            'id' => '981ee12c-559d-789a-6842-55e2e2a2d843',
            'relationship_name' => 'aos_contracts_documents',
            'lhs_module' => 'AOS_Contracts',
            'lhs_table' => 'aos_contracts',
            'lhs_key' => 'id',
            'rhs_module' => 'Documents',
            'rhs_table' => 'documents',
            'rhs_key' => 'id',
            'join_table' => 'aos_contracts_documents',
            'join_key_lhs' => 'aos_contracts_id',
            'join_key_rhs' => 'documents_id',
            'relationship_type' => 'many-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => 'default',
            'lhs_subpanel' => 'default',
            'is_custom' => true,
            'relationship_only' => false,
            'for_activities' => false,
            'from_studio' => false,
        ),
    'documents_modified_user' =>
        array(
            'id' => 'd0751c5e-cb49-75ed-2dcc-55e2e2c49103',
            'relationship_name' => 'documents_modified_user',
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'Documents',
            'rhs_table' => 'documents',
            'rhs_key' => 'modified_user_id',
            'join_table' => NULL,
            'join_key_lhs' => NULL,
            'join_key_rhs' => NULL,
            'relationship_type' => 'one-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => 'default',
            'lhs_subpanel' => 'default',
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => false,
        ),
    'documents_created_by' =>
        array(
            'id' => 'db000b01-9b4b-82c5-cd85-55e2e22ab1dc',
            'relationship_name' => 'documents_created_by',
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'Documents',
            'rhs_table' => 'documents',
            'rhs_key' => 'created_by',
            'join_table' => NULL,
            'join_key_lhs' => NULL,
            'join_key_rhs' => NULL,
            'relationship_type' => 'one-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => 'default',
            'lhs_subpanel' => 'default',
            'relationship_only' => false,
            'for_activities' => false,
            'is_custom' => false,
            'from_studio' => false,
        ),
    'documents_users_1' =>
        array(
            'id' => 'e43af11a-fef9-325c-bcad-55e2e221b58b',
            'relationship_name' => 'documents_users_1',
            'lhs_module' => 'Documents',
            'lhs_table' => 'documents',
            'lhs_key' => 'id',
            'rhs_module' => 'Users',
            'rhs_table' => 'users',
            'rhs_key' => 'id',
            'join_table' => 'documents_users_1_c',
            'join_key_lhs' => 'documents_users_1documents_ida',
            'join_key_rhs' => 'documents_users_1users_idb',
            'relationship_type' => 'one-to-many',
            'relationship_role_column' => NULL,
            'relationship_role_column_value' => NULL,
            'reverse' => '0',
            'deleted' => '0',
            'readonly' => true,
            'rhs_subpanel' => 'default',
            'lhs_subpanel' => 'default',
            'from_studio' => true,
            'is_custom' => true,
            'relationship_only' => false,
            'for_activities' => false,
        ),
);